NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.emirites.group2.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.emirites.group2.com-cert.pem
    OrganizationalUnitIdentifier: peer
